### PR TITLE
Add Linux Wayland support

### PR DESCRIPTION
**Pull request by aleasto**

### CODE REVIEW

**Comment by aleasto** [comment]
Uh CI failed because the random test happened to generate \x00, lol.

**Comment by spyoungtech** [comment]
> Uh CI failed because the random test happened to generate \x00, lol.

Interesting. Didn't realize that was an edge case 🤦‍♀️  I'll have to take another look at the Windows implementation to see if that can be fixed somehow.

In the meantime, the other actions didn't run because GitHub doesn't like running them for external PRs. I kicked off the actions build, but I think the test suite will have to be modified in order to properly test wayland.

**Comment by aleasto** [comment]
> but I think the test suite will have to be modified in order to properly test wayland.

Is linux tested at all? You'd need a graphical session to run either xclip or wl-copy

**Comment by spyoungtech** [comment]
Yeah, looks like the travis integration is broken so linux tests aren't running. Will see what I can do about that. The Linux tests use xvfb to emulate a headed x environment. 

I got a "fix" for the Windows null characters in #10

**Comment by aleasto** [comment]
Looks like `kwin_wayland --virtual` is enough to make wl-copy/wl-paste work, where kwin is the KDE wayland server/compositor

**Comment by spyoungtech** [comment]
Ok, I merged #10 to main, which switches all the CI over to GitHub Actions for Windows, MacOs, and Ubuntu. I'm guessing we would expand the matrix or add another workflow file for ubuntu+wayland -- we just want to make sure both xclip and wayland are tested.

For xclip, all that was needed is the x server and the `DISPLAY` environment variable. I'm hoping the same is true for wayland

**Comment by aleasto** [comment]
Added wayland to the test workflow matrix. It got a little convoluted but :shrug:

**Comment by spyoungtech** [comment]
Awesome. Looks good to me. Thanks for the contribution. I should have a release out in the next few days

**Comment by spyoungtech** [comment]
Released in [v0.6.0](https://github.com/spyoungtech/pyclip/releases/tag/v0.6.0) 🎉

**Pull request merged**
